---
title: "Example fitting MVMR to one-sample data"
author: "Tom Palmer"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 2
    code_download: true
    code_folding: show
    anchor_sections: true
---

```{r include=FALSE}
require("Hmisc")
```
`r Hmisc::hidingTOC(levels = 2)`

```{r setup, message=FALSE}
library(haven)
library(ivreg)
if (!requireNamespace("Statamarkdown", quietly = TRUE)) {
  remotes::install_github("Hemken/Statamarkdown")
}
library(Statamarkdown)
```

## Simulate data

```{r}
set.seed(12345)
n <- 2000
g1 <- rbinom(n, 2, .4) # genetic instruments
g2 <- rbinom(n, 2, .3)
g3 <- rbinom(n, 2, .25)
u <- rnorm(n) # unmeasured confounder
w <- runif(n) # measured confounder
x1 <- g1 + g2 + g3 + w + u + rnorm(n) # exposure 1
x2 <- .5*g1 - .5*g2 + 0*g3 + u + rnorm(n) # exposure 2
y <- x1 + 0.5*x2 + u + rnorm(n) # outcome
dat <- data.frame(g1, g2, g3, w, x1, x2, y)
write_dta(dat, "mvmr-example.dta")
```

## One-sample MVMR with TSLS in R

```{r}
fit <- ivreg(y ~ x1 + x2 + w | w + g1 + g2 + g3, data = dat)
summary(fit)
# Estimates with 95% CIs
cbind(coef(fit), confint.default(fit))
```

## One-sample MVMR with TSLS in Stata

```{stata}
use mvmr-example
ivregress 2sls y w (x1 x2 = g1 g2 g3)
estat endog
estat overid
```
